\input texinfo @c -*- texinfo -*-
@setfilename mmm.info
@settitle MMM Manual 0.1
@set language en

@copying
Copyright @copyright{} 2008 Pascal Hofmann
@end copying

@titlepage
@title MMM
@subtitle MySQL Master-Master Replication Manager
@author Pascal Hofmann

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c print Table of Contents
@contents


@ifnottex
@node Top
@top MMM
     
This manual is for MMM version 2.
@end ifnottex

     
@menu
@end menu

@node Overview
@chapter Overview
@cindex Overview

MMM (MySQL Master-Master Replication Manager) is a set of flexible scripts to perform monitoring/failover and management of MySQL Master-Master replication configurations (with only one node writable at any time). The toolset also has the ability to read balance standard master/slave configurations with any number of slaves, so you can use it to move virtual IP addresses around a group of servers depending on whether they are behind in replication. In addition to that, it also has scripts for data backups, resynchronization between nodes etc.

@*
The main functionality is provided through the following three scripts: 
@table @command
@item mmmd_mon
monitoring daemon which does all monitoring work and makes all decisions about roles moving and so on.
@item mmmd_agent
agent daemon which runs on each MySQL server and provides monitoring node with simple set of remote services.
@item mmm_control
simple script dedicated to management of the mmmd_mon processes by commands. 
@end table

@*
@node Typical use-cases
@chapter Typical use-cases
@cindex typical use-cases

Typical use cases of MMM will be described in the following two sections.

@section Two node setup
@image{mmm-sample-setup-1}
In two node master-master setup, MMM uses five IPs: single permanent IP for each node that is never changed, 2 reader IPs (read-only) and 1 writer IP (updates). Last three IPs are migrating between the nodes depending on node availability.

Normally (no replication failures, no replication delay etc) active master has 2 IPs (reader and writer), standby master - 1 IP (reader). In case of a failure, both - writer and reader roles migrate to the working node. 

@section Two masters + one/many slaves

TODO

@image{mmm-sample-setup-2}



@node Requirements
@chapter Requirements
@cindex Requirements

For an MMM setup with @var{n} MySQL servers, you'll need

@table @code
@item @var{n} + 1 hosts
One host for each MySQL server; one host for the MMM monitor.
@item 2 * (@var{n} + 1) IPs
One IP for each host (see above); one IP for the writer role; @var{n} IPs for one reader role per host.
@item monitor user
A MySQL user with privileges @code{REPLICATION CLIENT} for MMM monitor.
@item agent user
A MySQL user with privileges @code{SUPER, REPLICATION CLIENT, PROCESS} for MMM agent.
@item replication user
A MySQL user with privileges @code{REPLICATION SLAVE} used for replication.
@item tools user
A MySQL user with privileges @code{SUPER, REPLICATION CLIENT, RELOAD} for MMM tools.
@end table


@section Requirements - monitoring host

@itemize
@item perl with ithreads support
@item fping (if you want to run @command{mmmd_mon} as non-root user)
@item Perl modules:

@itemize @minus
@item Log::Log4perl
@item Mail::Send
@item Log::Dispatch
@item Time::HiRes
@item Net::Ping
@item Class:Singleton
@item Proc::Daemon
@item Algorithm::Diff
@item Thread::Queue
@end itemize

@end itemize


@section Requirements - nodes
One should set read-only=1 in the configuration of all MySQL servers, MMM will change that to read-only=0 on the host with the active_master_role.
@itemize
@item perl
@item iproute
@item send_arp (solaris)
@item Perl modules:

@itemize @minus
@item Algorithm::Diff
@item DBI and DBD::mysql
@item Log::Dispatch
@item Log::Log4perl
@item Mail::Send
@item Net::ARP (linux)
@item Proc::Daemon
@item Time::HiRes
@end itemize

@end itemize


@section Additional requirements for MMM tools
If you want to use the MMM tools (mmm_backup, mmm_restore, mmm_clone) you have to use LVM for the partition on which your MySQL databases and logs reside. @strong{Note:} You'll need free physical extends for the snapshots undo space (see @url{http://www.mysqlperformanceblog.com/2008/06/09/estimating-undo-space-needed-for-lvm-snapshot/, Estimating Undo Space needed for LVM Snapshot}).

@*
You'll also need the following perl modules:
@itemize
@item Path::Class
@item Data::Dumper
@end itemize


@include mmm_agent.texi
@include mmm_monitor.texi
@include mmm_control.texi
@include mmm_configuration.texi
@include mmm_logging.texi
@c @include mmm_internals.texi


@node Index
@unnumbered Index

@printindex cp


@bye
