#!/usr/bin/env perl

use strict;
use warnings FATAL => 'all';
use Config;
use English qw( PROGRAM_NAME );
use Log::Log4perl qw(:easy);
Log::Log4perl->easy_init($INFO);

# Include parts of the system
use MMM::Common::Config;
use MMM::Common::Socket;

# Read configuration
our $config = new MMM::Common::Config::;
$config->read('mmm_mon');
$config->check('CONTROL');

die "See '$0 help' for usage information" if (scalar(@ARGV) < 1);

my $socket = MMM::Common::Socket::create_sender($config->{monitor}->{ip}, $config->{monitor}->{port}, 10);
die "Can't connect to monitor daemon" unless ($socket && $socket->connected);

print $socket join(' ', @ARGV), "\nquit\n";
my $res = '';
my $line;
$res .= $line while ($line = <$socket>);
print $res, "\n";

exit(0);

