#!/usr/bin/env perl

use strict;
use warnings FATAL => 'all';
use English qw( PROGRAM_NAME );
use Log::Log4perl qw(:easy);
Log::Log4perl->easy_init($INFO);

use Cwd;
use File::Basename;
use Proc::Daemon;

# Define protocol version
use constant MMM_PROTOCOL_VERSION => 1;

# Determine installation dir name
our $SELF_DIR = dirname(dirname(Cwd::abs_path(__FILE__)));


# Include parts of the system
require $SELF_DIR . '/lib/Common/Config.pm';
require $SELF_DIR . '/lib/Common/PidFile.pm';
require $SELF_DIR . '/lib/Common/Role.pm';
require $SELF_DIR . '/lib/Common/Socket.pm';
require $SELF_DIR . '/lib/Common/Uptime.pm';

require $SELF_DIR . '/lib/Agent/Agent.pm';
require $SELF_DIR . '/lib/Agent/Helpers.pm';
require $SELF_DIR . '/lib/Agent/Role.pm';

MMM::Common::Log::init('mmm_agent_log.conf');

# Read configuration
our $config = new MMM::Common::Config::;
$config->read('mmm_agent');
$config->check('AGENT');

my $debug = 0;
$debug = 1 unless ($config->{debug} =~ /^(false|off|no|0)$/i);

MMM::Common::Log::debug() if ($debug);

our $agent	= new MMM::Agent::(
	protocol_version	=> 1,
	active_master		=> '',
	state				=> 'UNKNOWN'
);
$agent->from_config($config);

my $pidfilename = $config->{host}->{ $config->{this} }->{pid_path};
my $pidfile = new MMM::Common::PidFile:: $pidfilename;

# Check pid file
LOGDIE	"Can't run second copy of ", $PROGRAM_NAME	if ($pidfile->is_running());
WARN	"Unclean start - found stale pid file!"		if ($pidfile->exists());

unless ($debug) {
	# Go to background
	Proc::Daemon::Init();
	# Init logging again to re-open fds
	MMM::Common::Log::init('mmm_mon_log.conf');
}
$pidfile->create();

# Shutdown flag
our $shutdown = 0;

# Catch signals
$SIG{INT} = \&SignalHandler;
$SIG{TERM} = \&SignalHandler;

$agent->main();

# Remove pid file
$pidfile->remove();

INFO 'END';
exit(0);

#-----------------------------------------------------------------
sub SignalHandler() {
	INFO "Signal received: exiting...";
	$shutdown = 1;
}
