#! /bin/sh

### BEGIN INIT INFO
# Provides:          mmm_agentd
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MMM Agent Daemon
# Description:       Debian init script for the mysql-mmm agent daemon
### END INIT INFO

set -e

. /lib/lsb/init-functions

DESC='MMM Agent Daemon'
NAME='mmm_agentd'
PIDFILE="/var/run/mmm_agentd.pid"
DAEMON="/usr/sbin/mmm_agentd"
ENABLED=0

test -f /etc/default/mysql-mmm-agent && . /etc/default/mysql-mmm-agent

if [ "$ENABLED" = "0" ]; then
    log_action_msg "$DESC disabled, see /etc/default/mysql-mmm-agent"
    exit 0
fi

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    if pidofproc -p $PIDFILE >/dev/null; then
      log_progress_msg "already running"
      log_end_msg 0
      exit 0
    fi
    $DAEMON
    log_end_msg $?
    ;;

  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    if start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    ;;

  status)
    status_of_proc -p $PIDFILE $DAEMON "$NAME" && exit 0 || exit $?
    ;;

  restart|force-reload)
    $0 stop
    $0 start
    exit $?
    ;;

  *)
    log_action_msg "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;

esac

exit 0
